### ISSUE TITLE
Placing Mekanism Energy Cube freezes (crash) game

### ISSUE THREAD

**Issue by Krutoy242** [Red-Studio-Ragnarok/Fancier-Block-Particles#13]
## Describe the bug

I placing Mek's `Creative Energy Cube` and my game freezes. It looks like crash, but not crash report generated.

There is last thing i could see:

![dwm_RxP4ZjjqbU](https://user-images.githubusercontent.com/936618/209434830-77a87e53-6c05-4c00-b8c5-5133f90aa356.png)

## Specification:

- OS: Windows 10
- CPU: i5-7400 @ 3.00 GHz
- GPU: GTX 1050 Ti
- RAM Allocated: 6GB

## Additional context

Happen on [E2E-E](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended) modpack.

## Log

[debug-1.log.gz](https://github.com/Red-Studio-Ragnarok/Fancier-Block-Particles/files/10298489/debug-1.log.gz)

**Comment by JustDesoroxxx** [comment]
This sounds like #7 which has been fixed in dev builds so if you can try it out with a dev builds it would be nice.

**Comment by Krutoy242** [comment]
But I'm already using latest Dev version, you can see it in logs.
Is there any other Dev versions except ones in your discord?

**Comment by JustDesoroxxx** [comment]
No, there is no newer dev version I am currently not at home so I am not able to see the logs so I will need to look at them when I am back.

**Comment by Krutoy242** [comment]
P.S. you should add *version* and **logs** into your issue template.

**Comment by JustDesoroxxx** [comment]
After testing with only Mekanism and FBP I could not reproduce the issue

**Comment by JustDesoroxxx** [comment]
Seems to be a conflict with Waila

**Comment by JustDesoroxxx** [comment]
Fixed in 0.8-Dev-10
