### ISSUE TITLE
Log error `ClassNotFoundException: com.TominoCZ.FBP.FBP`

### ISSUE THREAD

**Issue by Krutoy242** [Red-Studio-Ragnarok/Fancier-Block-Particles#15]
I found that my debug.log have this lines of error:

```
 [Client thread/ERROR] [snowrealmagic]: Catching
java.lang.ClassNotFoundException: com.TominoCZ.FBP.FBP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_51]
	at snownee.snow.compat.FBPHack.hackFBP(FBPHack.java:14) [FBPHack.class:?]
```

[debug.log](https://github.com/Red-Studio-Ragnarok/Fancier-Block-Particles/files/10327218/debug.log)

Seems like they don't cause crashes. But i want to know what that error means.

<details>
  <summary>Additional context</summary>  
  
	Happen on E2E-E modpack https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended
    
	- OS: Windows 10
	- CPU: i5-7400 @ 3.00 GHz
	- GPU: GTX 1050 Ti
	- RAM Allocated: 6GB
  
</details>

**Comment by ACGaming** [comment]
Snow Real Magic has a compatibility hack for the original Fancy Block Particles. Don‘t know why it throws this error though because the class still exists.

**Comment by JustDesoroxxx** [comment]
> Snow Real Magic has a compatibility hack for the original Fancy Block Particles: https://github.com/Snownee/SnowRealMagic/blob/1.12/src/main/java/snownee/snow/compat/FBPHack.java Don‘t know why it throws this error though because the class still exists.

It doesn't anymore @Krutoy242 is using the dev builds that are found in my Discord server and is from the 0.8 branch which has been fully refactored.

This error is harmless maybe Snownee will fix the issue if you post it on their GitHub.

But pretty sure the fix is not needed in my version.

**Comment by JustDesoroxxx** [comment]
@Krutoy242 could you try if this is still happening with latest FBP dev build and with latest SnowRealMagic release

**Comment by Krutoy242** [comment]
I will later, thanks!

**Comment by JustDesoroxxx** [comment]
Tested it, it's fixed

**Comment by reddvilzz** [comment]
Sorry to reopened the thread, but for some reason the error still showing on mine, here is the [latest log](https://mclo.gs/1OpHav4)

I am using 0.8-dev-17 version.

**Comment by Desoroxxx** [comment]
> Sorry to reopened the thread, but for some reason the error still showing on mine, here is the [latest log](https://mclo.gs/1OpHav4)
> 
> I am using 0.8-dev-17 version.

Anwsered in the [SnowRealMagic issue](https://github.com/Snownee/SnowRealMagic/issues/404)
