### ISSUE TITLE
[Feature Request] Link Forge Mods Menu Config Button To The FBP Menu

### ISSUE THREAD

**Issue by Krutoy242** [Red-Studio-Ragnarok/Fancier-Block-Particles#17]
Since my modpack loading ~10 minutes, its hard to reload it each time i changing configs.

Especially, this related to bugs i discovered recently 😅  
I would like to blacklist `ic2:te` blocks from being animated to be able continue testing my Nuclear Reactor, but just discovered that i need to reload whole game for that.

![javaw_7jqHVwhhUe](https://user-images.githubusercontent.com/936618/210167611-bf606dc5-65e2-4693-9af1-3a6103841874.png)

**Comment by JustDesoroxxx** [comment]
You do not need to reload the whole game for that, if you go into the control menu you should see that by default a b and p key are assigned p I for the FBP menu and b is for the FBP blacklist menu

**Comment by Krutoy242** [comment]
Oh, I kinda forget about that. Now I remember that I read about block blacklist hotkey in mod description on CF.

But, this is still unconventional. Most mods finds a way to tell how they work from inside game, without needing to brouse Internet.

1. Since this mod have config screen, could you bind it to `[Config]` button above instead of hotkey?
2. Or, at least, can you write in "Mod Info" text (right side of screen), that player should press "B" or "P" to configure?

**Comment by JustDesoroxxx** [comment]
> But, this is still unconventional. Most mods finds a way to tell how they work from inside game, without needing to brouse Internet.
> 
> 1. Since this mod have config screen, could you bind it to `[Config]` button above instead of hotkey?

This is planned yes

**Comment by JustDesoroxxx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Forge mod menu config compatiblity](https://trello.com/c/8qM62xEP/44-forge-mod-menu-config-compatiblity)

**Comment by JustDesoroxxx** [comment]
Done in 0.8-Dev-11

**Comment by JustDesoroxxx** [comment]
Done in 0.8-Dev-11
