### ISSUE TITLE
Crash when breaking Forestry Multiblock Farm Blocks

### ISSUE THREAD

**Issue by MasterEnderman** [Red-Studio-Ragnarok/Fancier-Block-Particles#7]
## Describe the bug

The game crashes when you try to break a block from the Forestry Multiblock Farm.

## To Reproduce

***Steps to reproduce the behavior:***

1. place any [forestry multiblock farm block](https://ftb.fandom.com/wiki/Farm_Block)
2. try to break it -> [crash](https://mclo.gs/RfVWe38)
3. look at it -> try to open the blacklist menu -> [crash](https://mclo.gs/S9WEfTE)

**Comment by JustDesoroxxx** [comment]
What version of FBP are you using?

**Comment by JustDesoroxxx** [comment]
Could you try the same thing with Fancier Block Particles 0.6?

**Comment by JustDesoroxxx** [comment]
Fixed in 0.8 which will be out this Friday

**Comment by JustDesoroxxx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix crash with some modded blocks](https://trello.com/c/kOW9PNNH/1-fix-crash-with-some-modded-blocks)
